version: '3.8'

services:
  samba-vulnerable:
    build: .
    container_name: samba-vuln-4.23.1
    hostname: vuln-dc
    domainname: vulnerable.local
    networks:
      samba_net:
        ipv4_address: 172.20.0.10
    ports:
      - "8137:137/udp"
      - "8138:138/udp"
      - "139:139/tcp"
      - "8445:445/tcp"
      - "8389:389/tcp"
      - "8636:636/tcp"
      - "8088:88/tcp"
      - "8464:464/tcp"
    volumes:
      - samba-data:/usr/local/samba/private
      - samba-logs:/var/log/samba
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    stdin_open: true
    tty: true

networks:
  samba_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  samba-data:
  samba-logs:
