services:
  node-red:
    image: nodered/node-red:3.1.0-18
    ports:
      - "1880:1880"
    volumes:
      - node_red_data:/data
    devices:
      - /dev/gpiomem:/dev/gpiomem
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1880"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - scadanet
    extra_hosts:
      - "host.docker.internal:host-gateway"
  openplc:
    build:
      context: ./OpenPLC_v3
    ports:
      - "8080:8080"
      - "502:502"
    volumes:
      - openplc_data:/opt/openplc
    privileged : true
    devices:
      - /dev/gpiomem:/dev/gpiomem
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - scadanet
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  scadanet:
    driver: bridge
volumes:
  node_red_data:
  openplc_data:
